package com.task_management_project.commands.enums;

public enum CommandType {
    ADDCOMMENTTOTASK,
    ADDPERSONTOTEAM,
    CREATENEWBOARDINTEAM,
    CREATENEWPERSON,
    CREATENEWTEAM,
    SHOWALLPEOPLE,
    SHOWALLTEAMBOARDS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMS,
    SHOWBOARDACTIVITY,
    SHOWPERSONACTIVITY,
    SHOWTEAMACTIVITY,
}
